/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBookRouteImport } from './routes/api/public/book'
import { Route as ApiPublicAvailabilityRouteImport } from './routes/api/public/availability'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookRoute = ApiPublicBookRouteImport.update({
  id: '/api/public/book',
  path: '/api/public/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvailabilityRoute = ApiPublicAvailabilityRouteImport.update({
  id: '/api/public/availability',
  path: '/api/public/availability',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/availability': typeof ApiPublicAvailabilityRoute
  '/api/public/book': typeof ApiPublicBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/availability': typeof ApiPublicAvailabilityRoute
  '/api/public/book': typeof ApiPublicBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/availability': typeof ApiPublicAvailabilityRoute
  '/api/public/book': typeof ApiPublicBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/public/availability'
    | '/api/public/book'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/api/public/availability' | '/api/public/book'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/public/availability'
    | '/api/public/book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicAvailabilityRoute: typeof ApiPublicAvailabilityRoute
  ApiPublicBookRoute: typeof ApiPublicBookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/book': {
      id: '/api/public/book'
      path: '/api/public/book'
      fullPath: '/api/public/book'
      preLoaderRoute: typeof ApiPublicBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/availability': {
      id: '/api/public/availability'
      path: '/api/public/availability'
      fullPath: '/api/public/availability'
      preLoaderRoute: typeof ApiPublicAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicAvailabilityRoute: ApiPublicAvailabilityRoute,
  ApiPublicBookRoute: ApiPublicBookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
